metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: /paddle/datasets/coco/train2017
    anno_path: /paddle/datasets/coco/annotations/instances_train2017.json
    dataset_dir: /paddle/datasets/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: /paddle/datasets/coco/val2017
    anno_path: /paddle/datasets/coco/annotations/instances_val2017.json
    dataset_dir: /paddle/datasets/coco

TestDataset:
  !ImageFolder
    anno_path: /paddle/datasets/coco/annotations/instances_val2017.json
